### ISSUE TITLE
Define new tag

### ISSUE THREAD

**Issue by HamedFathi** [researchgate/doctrine-file#123]
Is it possible to [define a new custom tag](https://stackoverflow.com/questions/40263846/create-custom-tags-with-jsdoc) and parse it?
like

`@bindable {string} state - Represents the state of the component`

```js
{
    title: 'bindable',
    description: 'Represents the state of the component.',
    type: 'string',
    name: 'state'
}
```

**Comment by danez** [comment]
Unfortunately we rely on [eslint/doctrine](https://github.com/eslint/doctrine) for the actual parsing and this package was discontinued. So we will also discontinue this package in the foreseeable future.
